def show_help():
    print("\nAvailable commands:")
    print(" help  - Show available commands")
    print(" cd        - Change current directory")
    print(" pwd       - Show current working directory")
    print(" ls        - List files and directories")
    print(" hash  - Calculate file hashes")
    print(" fileinfo  - Show file information")
    print(" strings   - Extract readable strings")
    print(" scan      - Run automatic analysis")
    print(" exif      - Show image metadata")
    print(" interesting - Find URLs, IPs, emails and flags")
    print(" hex       - Show hexadecimal view")
    print(" entropy   - Calculate file entropy")
    print(" magic      - Detect file type using magic bytes")
    print(" peinfo    - Analyze Windows PE files")
    print(" imports   - Show imported DLL functions")
    print(" cat       - Display text file contents")
    print(" exit  - Exit Renzu\n")